# version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx 
    ports:
      - "443:443"
    networks:
      - myNet
    depends_on:
      - wordpress
      - redis
    volumes:
      - wordpress:/var/www/html
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - redis
      - mariadb
    networks:
      - myNet
    env_file:
      - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - myNet
    env_file:
      - .env
    volumes:
      - mariadb:/data
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - myNet
    ports:
      - "6379:6379"
    restart: always
  ftp:
    build: ./requirements/bonus/FTP_server
    container_name: ftp
    volumes:
      - wordpress:/var/www/html
    networks:
      - myNet
    env_file:
      - .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    restart: always
  adminer:
    build: requirements/bonus/Adminer
    container_name: adminer
    networks:
      - myNet
    ports:
      - 8081:8081
    restart: always
  static-site:
    build: requirements/bonus/static
    container_name: static-site
    networks:
      - myNet
    ports:
      - "8080:80"
    restart: always
  portainer:
    build: requirements/bonus/portainer
    container_name: portainer
    networks:
      - myNet
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: always

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/wordpress
      o: bind
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/mariadb
      o: bind
  portainer:
    name : portainer
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/portainer
      o: bind
networks:
  myNet:
    driver: bridge